package model

import "go.mongodb.org/mongo-driver/v2/bson"

type User struct {
	Id           bson.ObjectID   `bson:"_id,omitempty"` // Auto-generated by MongoDB
	Username     string          `bson:"username" validate:"required"`
	Email        string          `bson:"email" validate:"required"`
	PasswordHash string          `bson:"passwordHash" validate:"required"`
	Words        []LanguageWords `bson:"words"`
}
